/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames;

import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author AGONZALEZ
 */
public class Modificar extends javax.swing.JFrame {

    Statement st;
    PreparedStatement ps = null;
    ResultSet rs;

    /**
     * Creates new form CrearNuevo
     */
    public Modificar() {
        initComponents();txt_codigo.requestFocusInWindow();
       // btnguardar.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDescripcion3 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lblcodigo = new javax.swing.JLabel();
        lblDescripcion = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblDescripcion1 = new javax.swing.JLabel();
        lblDescripcion2 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        txt_marca = new javax.swing.JTextField();
        txt_hecho = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnactualizar = new javax.swing.JButton();
        btnhelp = new javax.swing.JButton();
        lblDescripcion4 = new javax.swing.JLabel();
        btnbuscarcodigo = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        lblDescripcion5 = new javax.swing.JLabel();
        txt_codigofisico = new javax.swing.JTextField();
        txt_potencia = new javax.swing.JTextField();
        txt_frecuencia = new javax.swing.JTextField();
        txt_frecuencia2 = new javax.swing.JTextField();
        txt_tension = new javax.swing.JTextField();
        txt_tension2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnvolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sounds - Generar Nuevo Label");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblDescripcion3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion3.setText("Tension:");
        jPanel1.add(lblDescripcion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, 37));

        txt_codigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_codigo.setText(" ");
        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        txt_codigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoKeyPressed(evt);
            }
        });
        jPanel1.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 290, 37));

        lblcodigo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcodigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcodigo.setText("Id:");
        jPanel1.add(lblcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 47, 40, 40));

        lblDescripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion.setText("Descripcion:");
        jPanel1.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 90, 37));

        lblMarca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMarca.setText("Marca:");
        jPanel1.add(lblMarca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 50, 37));

        lblDescripcion1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion1.setText("Hecho en:");
        jPanel1.add(lblDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 70, 37));

        lblDescripcion2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion2.setText("Consumo de Potencia:");
        jPanel1.add(lblDescripcion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 140, 37));

        txt_descripcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_descripcion.setText(" ");
        jPanel1.add(txt_descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, 290, 37));

        txt_marca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_marca.setText(" ");
        jPanel1.add(txt_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 290, 37));

        txt_hecho.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_hecho.setText(" ");
        jPanel1.add(txt_hecho, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 290, 37));

        jLabel1.setFont(new java.awt.Font("Britannic Bold", 0, 23)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setText("Modificar Label ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 170, 50));

        btnactualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnactualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/update.png"))); // NOI18N
        btnactualizar.setText("Actualizar");
        btnactualizar.setBorderPainted(false);
        btnactualizar.setContentAreaFilled(false);
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnactualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 320, 40));

        btnhelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/HELP2.png"))); // NOI18N
        btnhelp.setContentAreaFilled(false);
        btnhelp.setFocusPainted(false);
        btnhelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhelpActionPerformed(evt);
            }
        });
        jPanel1.add(btnhelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 450, 50, 50));

        lblDescripcion4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion4.setText("Frecuencia:");
        jPanel1.add(lblDescripcion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 70, 37));

        btnbuscarcodigo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/search.png"))); // NOI18N
        btnbuscarcodigo.setContentAreaFilled(false);
        btnbuscarcodigo.setFocusPainted(false);
        btnbuscarcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarcodigoActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuscarcodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 40, 35));

        btnlimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/limpiar.png"))); // NOI18N
        btnlimpiar.setContentAreaFilled(false);
        btnlimpiar.setFocusPainted(false);
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 37, 35));

        lblDescripcion5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblDescripcion5.setText("Codigo Fisico(Modelo)");
        jPanel1.add(lblDescripcion5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 140, 37));

        txt_codigofisico.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(txt_codigofisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 290, 37));

        txt_potencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_potencia.setText(" ");
        jPanel1.add(txt_potencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 290, 37));

        txt_frecuencia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_frecuencia.setText(" ");
        jPanel1.add(txt_frecuencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 87, 37));

        txt_frecuencia2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_frecuencia2.setText(" ");
        jPanel1.add(txt_frecuencia2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 98, 37));

        txt_tension.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tension.setText(" ");
        jPanel1.add(txt_tension, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 87, 37));

        txt_tension2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txt_tension2.setText(" ");
        jPanel1.add(txt_tension2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 94, 37));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 18, 23));
        jLabel2.setText("*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 40, 40));

        btnvolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/volver.png"))); // NOI18N
        btnvolver.setContentAreaFilled(false);
        btnvolver.setFocusPainted(false);
        btnvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnvolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 560, 500));

        jLabel3.setText("  ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 510, 30, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
       if (        txt_codigo.equals(" ")
                || txt_codigofisico.equals(" ")
                || txt_marca.equals(" ")
                || txt_hecho.equals(" ")
                || txt_descripcion.equals(" ")
                || txt_potencia.equals(" ")
                || txt_frecuencia.equals(" ")
                || txt_frecuencia2.equals(" ")
                || txt_tension.equals(" ")
                || txt_tension2.equals(" ")
               ) {

            JOptionPane.showMessageDialog(rootPane, "Falta un campo de llenar");

         
        } else {
             // JOptionPane.showMessageDialog(rootPane, "COmpleto!!!!");

             
             existecodigo();
        }   
        
        
        
        
    }//GEN-LAST:event_btnactualizarActionPerformed

    private void btnhelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhelpActionPerformed
     // ayudaboton();
    }//GEN-LAST:event_btnhelpActionPerformed

    private void btnbuscarcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarcodigoActionPerformed
        buscarcodigo();
    }//GEN-LAST:event_btnbuscarcodigoActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiarcampos();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            buscarcodigo();
        }
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            limpiarcampos();
        }

    }//GEN-LAST:event_txt_codigoKeyPressed

    private void btnvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvolverActionPerformed
        // TODO add your handling code here:
        
        Menu m=new Menu();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnvolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnbuscarcodigo;
    private javax.swing.JButton btnhelp;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnvolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblDescripcion1;
    private javax.swing.JLabel lblDescripcion2;
    private javax.swing.JLabel lblDescripcion3;
    private javax.swing.JLabel lblDescripcion4;
    private javax.swing.JLabel lblDescripcion5;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_codigofisico;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_frecuencia;
    private javax.swing.JTextField txt_frecuencia2;
    private javax.swing.JTextField txt_hecho;
    private javax.swing.JTextField txt_marca;
    private javax.swing.JTextField txt_potencia;
    private javax.swing.JTextField txt_tension;
    private javax.swing.JTextField txt_tension2;
    // End of variables declaration//GEN-END:variables

    public void RevisarCamposVacios() {
        if (txt_codigo.equals(" ")|| txt_descripcion.equals(" ")
                || txt_marca.equals(" ")|| txt_hecho.equals(" ")) 
        {
            JOptionPane.showMessageDialog(rootPane, "Faltan datos, si aparecen datos en blanco, comunicate con el comprador responsable");    
        } else {
       //   Revisar si existe el codigo();
        }
     }

    public void ExisteCodigo() {
        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://192.168.1.80:56704", "usounds", "madljda");
            st = conexion.createStatement();
            st.executeUpdate("USE  noms");
            rs = st.executeQuery("select codigo from noms1web where codigo='" + txt_codigo.getText() + "'");

            boolean variable = rs.next();

            String s1 = Boolean.toString(variable);

            try {
                if (s1.equals("false")) {
                    while (rs.next()) {///
                    }
                    // destinoventana();

                } else {
                    JOptionPane.showMessageDialog(null, "El codigo ya tiene Label --> " + txt_codigo.getText(), "Alerta", JOptionPane.WARNING_MESSAGE);
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);
        }

        
     }

    public void buscarcodigo() {
        String codigo = "";
        String codigof = "";
        String descripcion = "";
        String marca = "";
        String hecho = "";
        String importador = "";  
        String exportador = "";
        String tensionalimentacion = "";
        String tensionalimentacion2 = "";
        String consumopotencia = "";
        String frecuencia = "";
        String frecuencia2 = "";

        try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://192.168.1.80:56704", "usounds", "madljda");
            st = conexion.createStatement();
            st.executeUpdate("use cml;");

            rs = st.executeQuery("select codigo,codigofisico,descripcion,marca"
                    + ",hecho,tensionalimentacion,tensionalimentacion2,"
                    + "consumopotencia,frecuencia,frecuencia2 "
                    + "from nometiqueta where codigo='" + txt_codigo.getText().trim() + "' or codigofisico= '" +txt_codigo.getText().trim()+ "'");

            while (rs.next()) {

                codigo = rs.getString(1).trim();
                codigof = rs.getString(2).trim();
                descripcion = rs.getString(3).trim();
                marca = rs.getString(4).trim();
                hecho = rs.getString(5).trim();
                tensionalimentacion  = rs.getString(6).trim();
                tensionalimentacion2  = rs.getString(7).trim();
                consumopotencia  = rs.getString(8).trim();
                frecuencia  = rs.getString(9).trim();
                frecuencia2  = rs.getString(10).trim();
                 
                
            }
         
            txt_marca.setText(marca);
            txt_descripcion.setText(descripcion);
            txt_hecho.setText(hecho);
            txt_codigofisico.setText(codigof);
            txt_potencia.setText(consumopotencia);
            txt_frecuencia.setText(frecuencia);
            txt_frecuencia2.setText(frecuencia2);
            txt_tension.setText(tensionalimentacion);
            txt_tension2.setText(tensionalimentacion2);
            
            txt_codigo.setText(codigo);

            txt_codigo.setEditable(false);
            txt_codigo.setEnabled(false);
              btnactualizar.setEnabled(true);

        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la base de datos");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Modificar.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    public void limpiarcampos() {
        txt_descripcion.setText("");
        txt_codigofisico.setText("");
        txt_codigo.setText("");
        txt_marca.setText("");
        txt_hecho.setText("");
        txt_codigo.setEnabled(true);
        txt_codigo.setEditable(true);
        btnactualizar.setEnabled(false);
        txt_tension.setText("");
        txt_tension2.setText("");
        txt_frecuencia.setText("");
        txt_frecuencia2.setText("");
         txt_potencia.setText("");
    }
      public void confirmacodigo(){
     
     
     
      int result = JOptionPane.showConfirmDialog(null, "Seguro que quieres modificar el codigo?", "ATENCION",
                    JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            modificarcodigo();
        } else if (result == JOptionPane.NO_OPTION) {

        }     
     }
     public void existecodigo() {

         try {
             Class.forName("net.sourceforge.jtds.jdbc.Driver");
             java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://192.168.1.80:56704", "usounds", "madljda");
             st = conexion.createStatement();
             st.executeUpdate("USE CML");
             rs = st.executeQuery("select codigo from  NomEtiqueta where codigo='" + txt_codigo.getText() + "'");

             boolean variable = rs.next();
             String s1 = Boolean.toString(variable);

             try {
                 if (s1.equals("false")) {
                     while (rs.next()) {
                     }
                     JOptionPane.showMessageDialog(null, "El codigo " + txt_codigo.getText().trim() + " no esta registrado", "Alerta", JOptionPane.WARNING_MESSAGE);


                 } else {
                      confirmacodigo();
                     
                }
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane, ex.getMessage());
             }
         } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
     public void modificarcodigo(){
      
         
         
         
         try {
            Class.forName("net.sourceforge.jtds.jdbc.Driver");
            java.sql.Connection conexion = DriverManager.getConnection("jdbc:jtds:sqlserver://192.168.1.80:56704", "usounds", "madljda");
            Statement st = conexion.createStatement();
            st.executeUpdate("USE cml;");

             ps = conexion.prepareStatement("update nometiqueta set codigofisico='"+txt_codigofisico.getText().trim()+"',\n"
                     + "descripcion='"+txt_descripcion.getText().trim()+"',marca='"+txt_marca.getText().trim()+"',\n"
                     + "hecho='"+txt_hecho.getText().trim() +"',tensionalimentacion='" + txt_tension.getText().trim() +"',\n"
                     + "tensionalimentacion2='" + txt_tension2.getText().trim() +"',ConsumoPotencia='" + txt_potencia.getText().trim() +"',\n"
                     + "frecuencia='" + txt_frecuencia.getText().trim() +"',frecuencia2='" + txt_frecuencia2.getText().trim() +"'\n"
                     + " where codigo='" + txt_codigo.getText().trim() +"'");

             int n = ps.executeUpdate();
            if (n > 0) {
                JOptionPane.showMessageDialog(null, "¡Los datos han sido guardados exitósamente!");
                st.close();
                   limpiarcampos();
            }
        } catch (HeadlessException | SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Error en la base de datos" + ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(CrearNuevo.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
}
